Add new story
quarcs-lab/quarcs-bolivia pull request #98
Opened 2023-10-04 14:42 UTC by karestrepo

2023-10-04 23:42 UTC, Mose-Skolnick submitted a review, later dismissed

2023-10-10 01:38 UTC, GeoffreyXue requested changes
Looks good! Just a couple of minor cleanup changes

2023-10-10 01:38 UTC, GeoffreyXue commented on content/topics/sdg2-zero-hunger/stories/Katerine-Restrepo-1/index.md
> +{{< paragraph class="large" >}}
```suggestion
```

2023-10-10 01:38 UTC, GeoffreyXue commented on content/topics/sdg2-zero-hunger/stories/Katerine-Restrepo-1/index.md
> +deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d-c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortality%2
```suggestion
links:
    deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d- c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortality%20and%20Nutrition%20in%20Bolivia-84beb61d25a44593b6f174613c80f259"
```

2023-10-10 01:39 UTC, GeoffreyXue commented on content/topics/sdg2-zero-hunger/stories/Katerine-Restrepo-1/index.md
> +deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d-c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortality%2
The motivation for changing this from just the deepnote to be prefixed with links is due to #96, where the `links` front matter was introduced, ideally replacing the `deepnote` link that is currently available. More explanation can be found on the PR above.

2023-10-10 01:46 UTC, GeoffreyXue commented
One final change @karestrepo, could you please rename the file to `story.md`? It was a more recent change to differentiate stories for now, since Hugo treats files named `index.md` in a particular way, which is not really the intended case for stories.

More on this: https://gohugo.io/content-management/page-bundles/

2023-10-10 01:52 UTC, GeoffreyXue requested changes
One that thing that was on me

2023-10-10 01:52 UTC, GeoffreyXue commented on content/topics/sdg2-zero-hunger/stories/Katerine-Restrepo-1/story.md
> +    deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d- c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortal
```suggestion
  deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d- c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortality%20and%20Nutrition%20in%20Bolivia-84beb61d25a44593b6f174613c80f259"
```
Sorry, added two extra spaces here

2023-10-10 01:54 UTC, GeoffreyXue commented on content/topics/sdg2-zero-hunger/stories/Katerine-Restrepo-1/story.md
> +  deepnote: "https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d- c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortalit
```suggestion
  deepnote: https://deepnote.com/workspace/nagoya-university-102f-072bbb53-844b-47b1-aa0d- c8654cf05167/project/Nutritional-Inequality-b5441f3b-b9ff-452a-a4cf-3a2ce6025e8d/notebook/Infant%20Mortality%20and%20Nutrition%20in%20Bolivia-84beb61d25a44593b6f174613c80f259
```

Hmm, still not rendering. One more try?

2023-10-10 01:58 UTC, GeoffreyXue commented
Ah I see, it seems like the branch is just out of date with master. I'll update the PR really quick (just doing a `git merge origin/main`

2023-10-10 01:59 UTC, GeoffreyXue commented
> Ah I see, it seems like the branch is just out of date with master. I'll update the PR really quick (just doing a `git merge origin/main`

For more clarification on this - this branch wasn't up to date with the changes I made in previous commits, so the links weren't rendering. I've now pulled in the changes since this branch was created, and hopefully it will now correctly render the links.

2023-10-10 02:00 UTC, GeoffreyXue approved these changes
Looks like it's working now!

2023-10-10 02:00 UTC, merged

2023-10-10 02:27 UTC, karestrepo commented
the  deepnote link is not working